In [1]:
import pandas as pd

In [2]:
from datetime import datetime

# Times

In [3]:
times = pd.read_csv("times_ids.csv")

In [4]:
times

,nome.cbf,nome.cartola,nome.completo,cod.older,cod.2017,cod.2018,id,abreviacao,escudos.60x60,escudos.45x45,escudos.30x30
0,América - MG,América-MG,America MG,327,327,327,327,AME,https://s.glbimg.com/es/sde/f/organizacoes/201...,https://s.glbimg.com/es/sde/f/organizacoes/201...,https://s.glbimg.com/es/sde/f/organizacoes/201...
1,America - RN,Atlético-RN,America RN,200,200,1,200,OUT,NaN,NaN,NaN
2,Atlético - GO,Atlético-GO,Atletico GO,201,373,373,373,ATL,NaN,NaN,NaN
3,Atlético - MG,Atlético-MG,Atletico Mineiro,282,282,282,282,ATL,https://s.glbimg.com/es/sde/f/equipes/2017/11/...,https://s.glbimg.com/es/sde/f/equipes/2017/11/...,https://s.glbimg.com/es/sde/f/equipes/2017/11/...
4,Atlético - PR,Atlético-PR,Atletico Paranaense,293,293,293,293,ATL,https://s.glbimg.com/es/sde/f/equipes/2015/06/...,https://s.glbimg.com/es/sde/f/equipes/2015/06/...,https://s.glbimg.com/es/sde/f/equipes/2015/06/...
5,Atletico - PR,Atlético-PR,Atletico Paranaense,293,293,293,293,ATL,https://s.glbimg.com/es/sde/f/equipes/2015/06/...,https://s.glbimg.com/es/sde/f/equipes/2015/06/...,https://s.glbimg.com/es/sde/f/equipes/2015/06/...
6,Athlético-PR,Athlético-PR,Atletico Paranaense,293,293,293,293,ATL,NaN,NaN,NaN
7,Avaí - SC,Avaí,Avai FC,202,314,314,314,AVA,NaN,NaN,NaN
8,Bahia - BA,Bahia,EC Bahia,207,265,265,265,BAH,https://s.glbimg.com/es/sde/f/equipes/2014/04/...,https://s.glbimg.com/es/sde/f/equipes/2013/12/...,https://s.glbimg.com/es/sde/f/equipes/2013/12/...
9,Botafogo - RJ,Botafogo,Botafogo RJ,263,263,263,263,BOT,https://s.glbimg.com/es/sde/f/equipes/2014/04/...,https://s.glbimg.com/es/sde/f/equipes/2013/12/...,https://s.glbimg.com/es/sde/f/equipes/2013/12/...
10,Brasiliense,Brasiliense,Brasiliense,203,203,388,203,BRA,NaN,NaN,NaN
11,Ceará - CE,Ceará-SC,Ceara SC,204,204,354,354,CEA,https://s.glbimg.com/es/sde/f/equipes/2018/05/...,https://s.glbimg.com/es/sde/f/equipes/2018/05/...,https://s.glbimg.com/es/sde/f/equipes/2018/05/...
12,Ceará - CE,Ceará,Ceara SC,204,204,354,354,CEA,https://s.glbimg.com/es/sde/f/equipes/2018/05/...,https://s.glbimg.com/es/sde/f/equipes/2018/05/...,https://s.glbimg.com/es/sde/f/equipes/2018/05/...
13,Ceará - CE,Ceará-SC,Ceara SC,204,204,354,354,CEA,https://s.glbimg.com/es/sde/f/equipes/2018/05/...,https://s.glbimg.com/es/sde/f/equipes/2018/05/...,https://s.glbimg.com/es/sde/f/equipes/2018/05/...
14,Chapecoense - SC,Chapecoense,Chapecoense,315,315,315,315,CHA,https://s.glbimg.com/es/sde/f/equipes/2015/08/...,https://s.glbimg.com/es/sde/f/equipes/2015/08/...,https://s.glbimg.com/es/sde/f/equipes/2015/08/...
15,Clube Nautico,Náutico,Clube Nautico,205,205,343,205,NAU,NaN,NaN,NaN
16,Corinthians - SP,Corinthians,Corinthians SP,264,264,264,264,COR,https://s.glbimg.com/es/sde/f/equipes/2014/04/...,https://s.glbimg.com/es/sde/f/equipes/2013/12/...,https://s.glbimg.com/es/sde/f/equipes/2013/12/...
17,Coritiba - PR,Coritiba,Coritiba FC,294,294,294,294,COR,NaN,NaN,NaN
18,Criciuma - SC,Criciuma,Criciuma EC,206,206,288,206,CRI,NaN,NaN,NaN
19,Cruzeiro - MG,Cruzeiro,Cruzeiro EC,283,283,283,283,CRU,https://s.glbimg.com/es/sde/f/equipes/2015/04/...,https://s.glbimg.com/es/sde/f/equipes/2015/04/...,https://s.glbimg.com/es/sde/f/equipes/2015/04/...
20,CSA,CSA,CSA,341,341,341,341,CSA,NaN,NaN,NaN
21,Figueirense - SC,Figueirense,Figueirense,316,316,316,316,FIG,NaN,NaN,NaN
22,Flamengo - RJ,Flamengo,Flamengo RJ,262,262,262,262,FLA,https://s.glbimg.com/es/sde/f/equipes/2018/04/...,https://s.glbimg.com/es/sde/f/equipes/2018/04/...,https://s.glbimg.com/es/sde/f/equipes/2018/04/...
23,Fluminense - RJ,Fluminense,Fluminense RJ,266,266,266,266,FLU,https://s.glbimg.com/es/sde/f/equipes/2015/07/...,https://s.glbimg.com/es/sde/f/equipes/2015/07/...,https://s.glbimg.com/es/sde/f/equipes/2015/07/...
24,Fortaleza,Fortaleza,Fortaleza,209,209,356,356,FOR,NaN,NaN,NaN
25,Goiás - GO,Goiás,Goias EC,210,210,290,290,GOI,NaN,NaN,NaN
26,Grêmio - RS,Grêmio,Gremio Porto Alegre,284,284,284,284,GRE,https://s.glbimg.com/es/sde/f/equipes/2014/04/...,https://s.glbimg.com/es/sde/f/equipes/2013/12/...,https://s.glbimg.com/es/sde/f/equipes/2013/12/...
27,Gremio Barueri,Grêmio Barueri,Gremio Barueri,211,211,1,211,OUT,NaN,NaN,NaN
28,Gremio Prudente,Grêmio Prudente,Gremio Prudente,212,212,2554,212,PRU,NaN,NaN,NaN
29,Guarani FC,Guarani,Guarani FC,213,213,279,213,GUA,NaN,NaN,NaN
30,Internacional - RS,Internacional,Internacional,285,285,285,285,INT,https://s.glbimg.com/es/sde/f/equipes/2016/05/...,https://s.glbimg.com/es/sde/f/equipes/2016/05/...,https://s.glbimg.com/es/sde/f/equipes/2016/05/...
31,Ipatinga FC,Ipatinga,Ipatinga FC,214,214,1349,214,IPA,NaN,NaN,NaN
32,Joinville - SC,Joinville,Joinville EC,215,215,317,215,JEC,NaN,NaN,NaN
33,Juventude - RS,Juventude,Juventude RS,216,216,286,216,JUV,NaN,NaN,NaN
34,Paysandu - SC,Paysandu,Paysandu SC,218,218,291,218,PAY,NaN,NaN,NaN
35,Palmeiras - SP,Palmeiras,SE Palmeiras,275,275,275,275,PAL,https://s.glbimg.com/es/sde/f/equipes/2014/04/...,https://s.glbimg.com/es/sde/f/equipes/2013/12/...,https://s.glbimg.com/es/sde/f/equipes/2013/12/...
36,Paraná - PR,Paraná,Parana Clube,217,217,289,217,PAR,https://s.glbimg.com/es/sde/f/equipes/2014/04/...,https://s.glbimg.com/es/sde/f/equipes/2014/04/...,https://s.glbimg.com/es/sde/f/equipes/2014/04/...
37,Ponte Preta - SP,Ponte Preta,Ponte Preta,303,303,303,303,PON,NaN,NaN,NaN
38,Portuguesa,Portuguesa,Portuguesa,219,219,278,219,POR,NaN,NaN,NaN
39,Santa Cruz - PE,Santa Cruz,Santa Cruz FC,344,344,344,344,STC,NaN,NaN,NaN
40,Santo Andre EC,Santo André,Santo Andre EC,220,220,306,220,SAN,NaN,NaN,NaN
41,Santos - SP,Santos,Santos FC,277,277,277,277,SAN,https://s.glbimg.com/es/sde/f/equipes/2014/04/...,https://s.glbimg.com/es/sde/f/equipes/2013/12/...,https://s.glbimg.com/es/sde/f/equipes/2013/12/...
42,São Caetano,São Caetano,São Caetano,221,221,386,221,SAO,NaN,NaN,NaN
43,São Paulo - SP,São Paulo,Sao Paulo FC,276,276,276,276,SAO,https://s.glbimg.com/es/sde/f/equipes/2014/04/...,https://s.glbimg.com/es/sde/f/equipes/2013/12/...,https://s.glbimg.com/es/sde/f/equipes/2013/12/...
44,Sport - PE,Sport,Sport Club Recife,292,292,292,292,SPO,https://s.glbimg.com/es/sde/f/equipes/2015/07/...,https://s.glbimg.com/es/sde/f/equipes/2015/07/...,https://s.glbimg.com/es/sde/f/equipes/2015/07/...
45,Vasco da Gama - RJ,Vasco,Vasco da Gama,221,267,267,267,VAS,https://s.glbimg.com/es/sde/f/equipes/2016/07/...,https://s.glbimg.com/es/sde/f/equipes/2016/07/...,https://s.glbimg.com/es/sde/f/equipes/2016/07/...
46,Vitória - BA,Vitória,EC Vitoria BA,287,287,287,287,VIT,https://s.glbimg.com/es/sde/f/equipes/2014/04/...,https://s.glbimg.com/es/sde/f/equipes/2013/12/...,https://s.glbimg.com/es/sde/f/equipes/2013/12/...

# Tratando os dados de 2014 a 2020

As planilhas de 2014 a 2017 são idênticas, as planilhas de 2019 e 2020 também são, a planilha de 2018 é diferente das demais. Iremos padronizar as planilhas e unificá-las em uma única planilha. Dados desnecessários serão removidos e adicionados os campos necessários conforme a planilha em questão

# Partidas de 2014 a 2017

In [5]:
partidas_2014 = pd.read_csv("2014_partidas.csv")

In [6]:
partidas_2014.insert(0, "ano", 2014, True)

In [7]:
partidas_2015 = pd.read_csv("2015_partidas.csv")

In [8]:
partidas_2015.insert(0, "ano", 2015, True)

In [9]:
partidas_2016 = pd.read_csv("2016_partidas.csv")

In [10]:
partidas_2016.insert(0, "ano", 2016, True)

In [11]:
partidas_2017 = pd.read_csv("2017_partidas.csv")

In [12]:
partidas_2017.insert(0, "ano", 2017, True)

In [13]:
partidas_2014_a_2017 = pd.concat([partidas_2014, partidas_2015, partidas_2016, partidas_2017])

In [14]:
partidas_2014_a_2017 = partidas_2014_a_2017.drop(columns=["X", "Unnamed: 0", "arena"])

In [15]:
partidas_2014_a_2017

,ano,game,round,date,home_team,score,away_team
0,2014,1,1,20/04/2014 - 18:30,Flamengo - RJ,0 x 0,Goiás - GO
1,2014,2,1,19/04/2014 - 18:30,Fluminense - RJ,3 x 0,Figueirense - SC
2,2014,3,1,20/04/2014 - 16:00,São Paulo - SP,3 x 0,Botafogo - RJ
3,2014,4,1,20/04/2014 - 18:30,Santos - SP,1 x 1,Sport - PE
4,2014,5,1,20/04/2014 - 16:00,Atletico - PR,1 x 0,Grêmio - RS
...,...,...,...,...,...,...,...
375,2017,376,38,03/12/2017 - 17:00,Atlético - PR,3 x 0,Palmeiras - SP
376,2017,377,38,03/12/2017 - 17:00,Sport - PE,1 x 0,Corinthians - SP
377,2017,378,38,03/12/2017 - 17:00,Vitória - BA,1 x 2,Flamengo - RJ
378,2017,379,38,03/12/2017 - 17:00,Atlético - GO,1 x 1,Fluminense - RJ
379,2017,380,38,03/12/2017 - 17:00,Chapecoense - SC,2 x 1,Coritiba - PR

In [16]:
partidas_2014_a_2017.insert(7, "home_score", partidas_2014["score"].map(lambda x: x.split(" x ")[0]), False)

In [17]:
partidas_2014_a_2017.insert(8, "away_score", partidas_2014["score"].map(lambda x: x.split(" x ")[1]), False)

In [18]:
partidas_2014_a_2017

,ano,game,round,date,home_team,score,away_team,home_score,away_score
0,2014,1,1,20/04/2014 - 18:30,Flamengo - RJ,0 x 0,Goiás - GO,0,0
1,2014,2,1,19/04/2014 - 18:30,Fluminense - RJ,3 x 0,Figueirense - SC,3,0
2,2014,3,1,20/04/2014 - 16:00,São Paulo - SP,3 x 0,Botafogo - RJ,3,0
3,2014,4,1,20/04/2014 - 18:30,Santos - SP,1 x 1,Sport - PE,1,1
4,2014,5,1,20/04/2014 - 16:00,Atletico - PR,1 x 0,Grêmio - RS,1,0
...,...,...,...,...,...,...,...,...,...
375,2017,376,38,03/12/2017 - 17:00,Atlético - PR,3 x 0,Palmeiras - SP,2,1
376,2017,377,38,03/12/2017 - 17:00,Sport - PE,1 x 0,Corinthians - SP,0,1
377,2017,378,38,03/12/2017 - 17:00,Vitória - BA,1 x 2,Flamengo - RJ,1,1
378,2017,379,38,03/12/2017 - 17:00,Atlético - GO,1 x 1,Fluminense - RJ,1,2
379,2017,380,38,03/12/2017 - 17:00,Chapecoense - SC,2 x 1,Coritiba - PR,4,2

In [19]:
partidas_2014_a_2017 = partidas_2014_a_2017[["ano", "home_team", "away_team", "home_score", "away_score"]]

In [20]:
partidas_2014_a_2017

      ano         home_team         away_team home_score away_score
0    2014     Flamengo - RJ        Goiás - GO          0          0
1    2014   Fluminense - RJ  Figueirense - SC          3          0
2    2014    São Paulo - SP     Botafogo - RJ          3          0
3    2014       Santos - SP        Sport - PE          1          1
4    2014     Atletico - PR       Grêmio - RS          1          0
..    ...               ...               ...        ...        ...
375  2017     Atlético - PR    Palmeiras - SP          2          1
376  2017        Sport - PE  Corinthians - SP          0          1
377  2017      Vitória - BA     Flamengo - RJ          1          1
378  2017     Atlético - GO   Fluminense - RJ          1          2
379  2017  Chapecoense - SC     Coritiba - PR          4          2

[1520 rows x 5 columns]

# Partidas 2018

In [21]:
partidas_2018 = pd.read_csv("2018_partidas.csv")

In [22]:
partidas_2018 = partidas_2018.drop(columns=["arena"])

In [23]:
partidas_2018.insert(0, "ano", 2018, True)

In [24]:
partidas_2018.insert(7, "home_score", partidas_2018["score"].map(lambda x: x.split(" x ")[0]), False)

In [25]:
partidas_2018.insert(8, "away_score", partidas_2018["score"].map(lambda x: x.split(" x ")[1]), False)

In [26]:
partidas_2018 = partidas_2018[["ano", "home_team", "away_team", "home_score", "away_score"]]

In [27]:
partidas_2018

      ano           home_team           away_team home_score away_score
0    2018       Cruzeiro - MG         Grêmio - RS          0          1
1    2018       Atlético - PR    Chapecoense - SC          5          1
2    2018        América - MG          Sport - PE          3          0
3    2018        Vitória - BA       Flamengo - RJ          2          2
4    2018  Vasco da Gama - RJ       Atlético - MG          2          1
..    ...                 ...                 ...        ...        ...
375  2018     Fluminense - RJ        América - MG          1          0
376  2018          Ceará - CE  Vasco da Gama - RJ          0          0
377  2018          Sport - PE         Santos - SP          2          1
378  2018      Palmeiras - SP        Vitória - BA          3          2
379  2018         Grêmio - RS    Corinthians - SP          1          0

[380 rows x 5 columns]

# Partidas 2019

In [28]:
partidas_2019 = pd.read_csv("2019_partidas.csv")

In [29]:
partidas_2019.insert(0, "ano", 2019, True)

In [30]:
partidas_2020 = pd.read_csv("2020_partidas.csv")

In [31]:
partidas_2020.insert(0, "ano", 2020, True)

In [32]:
partidas_2019_a_2020 = pd.concat([partidas_2019, partidas_2020])

In [33]:
partidas_2019_a_2020 = partidas_2019_a_2020.rename(columns = {'home_team': 'home_team_cod', 'away_team': 'away_team_cod'}, inplace = False)

In [34]:
partidas_2019_a_2020

,ano,date,home_team_cod,away_team_cod,home_score,away_score,round
0,2019,2019-04-27,282,314,2,1,1
1,2019,2019-04-27,315,285,2,0,1
2,2019,2019-04-27,262,283,3,1,1
3,2019,2019-04-27,276,263,2,0,1
4,2019,2019-04-28,293,267,4,1,1
...,...,...,...,...,...,...,...
385,2020,2021-02-25,293,292,2,0,38
386,2020,2021-02-25,354,263,2,1,38
387,2020,2021-02-25,354,263,2,1,38
388,2020,2021-02-25,373,294,3,1,38
389,2020,2021-02-25,373,294,3,1,38

**Incosistência encontrada**

O time de id 280 não está na tabela de times. Porém, pelos resultados e o ano sabemos que este time é o Bragantino

In [35]:
partidas_2020.loc[~partidas_2020["home_team"].isin(times['id'])]

      ano        date  home_team  away_team  home_score  away_score  round
10   2020  2020-08-12        280        263           1           1      2
31   2020  2020-08-19        280        266           2           1      4
46   2020  2020-08-23        280        294           1           2      5
73   2020  2020-09-06        280        275           1           2      8
102  2020  2020-09-19        280        354           4           2     11
122  2020  2020-10-03        280        264           0           0     13
139  2020  2020-10-08        280        285           0           2     14
166  2020  2020-10-18        280        292           2           0     17
171  2020  2020-10-24        280        290           2           0     18
195  2020  2020-11-08        280        277           1           1     20
210  2020  2020-11-20        280        265           4           0     21
240  2020  2020-12-12        280        356           2           1     25
256  2020  2020-12-20        280        293           0           1     26
275  2020  2021-01-06        280        276           4           2     28
288  2020  2021-01-11        280        282           2           2     29
305  2020  2021-01-20        280        267           4           1     31
331  2020  2021-02-03        280        373           2           0     34
342  2020  2021-02-07        280        262           1           1     35
376  2020  2021-02-25        280        284           1           0     38
377  2020  2021-02-25        280        284           1           0     38

In [36]:
partidas_2019_a_2020.insert(2, "home_team", partidas_2019_a_2020["home_team_cod"].map(lambda x: 'Bragantino' if x == 280 else times.loc[times['id'] == x]['nome.cbf'].values[0]), False)

In [37]:
partidas_2019_a_2020.insert(3, "away_team", partidas_2019_a_2020["away_team_cod"].map(lambda x:'Bragantino' if x == 280 else times.loc[times['id'] == x]['nome.cbf'].values[0]), False)

In [38]:
partidas_2019_a_2020 = partidas_2019_a_2020[["ano", "home_team", "away_team", "home_score", "away_score"]]

In [39]:
partidas_2019_a_2020

      ano         home_team           away_team  home_score  away_score
0    2019     Atlético - MG           Avaí - SC           2           1
1    2019  Chapecoense - SC  Internacional - RS           2           0
2    2019     Flamengo - RJ       Cruzeiro - MG           3           1
3    2019    São Paulo - SP       Botafogo - RJ           2           0
4    2019     Atlético - PR  Vasco da Gama - RJ           4           1
..    ...               ...                 ...         ...         ...
385  2020     Atlético - PR          Sport - PE           2           0
386  2020        Ceará - CE       Botafogo - RJ           2           1
387  2020        Ceará - CE       Botafogo - RJ           2           1
388  2020     Atlético - GO       Coritiba - PR           3           1
389  2020     Atlético - GO       Coritiba - PR           3           1

[770 rows x 5 columns]

**Juntando tudo**

In [40]:
result = pd.concat([partidas_2014_a_2017, partidas_2018, partidas_2019_a_2020])

In [41]:
result

      ano        home_team         away_team home_score away_score
0    2014    Flamengo - RJ        Goiás - GO          0          0
1    2014  Fluminense - RJ  Figueirense - SC          3          0
2    2014   São Paulo - SP     Botafogo - RJ          3          0
3    2014      Santos - SP        Sport - PE          1          1
4    2014    Atletico - PR       Grêmio - RS          1          0
..    ...              ...               ...        ...        ...
385  2020    Atlético - PR        Sport - PE          2          0
386  2020       Ceará - CE     Botafogo - RJ          2          1
387  2020       Ceará - CE     Botafogo - RJ          2          1
388  2020    Atlético - GO     Coritiba - PR          3          1
389  2020    Atlético - GO     Coritiba - PR          3          1

[2670 rows x 5 columns]