In [1]:
import pandas as pd

In [2]:
dados_agregados_2014_2017 = pd.read_csv("dados_agregados_limpos.csv")

In [3]:
dados_agregados_2014_2017

,A,Apelido,AtletaID,CA,CV,ClubeID,DD,DP,FC,FD,...,away.score.x,dia,home.attack,home.defend,home.score.x,mes,pred.away.score,pred.home.score,risk_points,variable
0,0.0,Juan,36540,1.0,0.0,Internacional,0.0,0.0,2.0,0.0,...,0.0,19.0,0.0,0.0,1.0,4.0,0.0,0.0,1.000000,home.team
1,0.0,Juan,36540,0.0,0.0,Internacional,0.0,0.0,2.0,1.0,...,2.0,27.0,0.0,0.0,2.0,4.0,0.0,0.0,1.000000,away.team
2,0.0,Juan,36540,1.0,0.0,Internacional,0.0,0.0,2.0,0.0,...,1.0,4.0,0.0,0.0,2.0,5.0,0.0,0.0,1.000000,home.team
3,0.0,Juan,36540,0.0,0.0,Internacional,0.0,0.0,0.0,1.0,...,1.0,10.0,0.0,0.0,2.0,5.0,0.0,0.0,1.000000,home.team
4,0.0,Juan,36540,1.0,0.0,Internacional,0.0,0.0,5.0,0.0,...,0.0,18.0,0.0,0.0,0.0,5.0,0.0,0.0,1.000000,away.team
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17562,1.0,Tiago,79042,0.0,0.0,Atlético-MG,0.0,0.0,0.0,0.0,...,2.0,19.0,0.0,0.0,4.0,11.0,0.0,0.0,3.743454,away.team
17563,0.0,Nenén,79892,0.0,0.0,Chapecoense,0.0,0.0,-2.0,0.0,...,0.0,19.0,0.0,0.0,1.0,11.0,0.0,0.0,0.692901,home.team
17564,0.0,Cleberson,80281,1.0,0.0,Atlético-PR,0.0,0.0,3.0,0.0,...,3.0,18.0,0.0,0.0,3.0,11.0,0.0,0.0,0.505964,home.team
17565,0.0,Nenén,79892,-1.0,0.0,Chapecoense,0.0,0.0,-2.0,0.0,...,0.0,22.0,0.0,0.0,0.0,11.0,0.0,0.0,0.720802,away.team
17566,0.0,Douglas Grolli,78407,1.0,0.0,Cruzeiro,0.0,0.0,1.0,0.0,...,0.0,29.0,0.0,0.0,3.0,11.0,0.0,0.0,1.636392,home.team

In [4]:
dados_agregados_2014_2017 = dados_agregados_2014_2017[['ano', 'Apelido', 'AtletaID', 'ClubeID', 'Posicao', 'Pontos']]

In [6]:
media_pontos = dados_agregados_2014_2017.groupby(['ano', 'Apelido', 'AtletaID', 'ClubeID', 'Posicao']).mean('Pontos').reset_index()

In [10]:
media_pontos

       ano          Apelido  AtletaID        ClubeID Posicao    Pontos
0     2014            Abuda     79193    Chapecoense     mei  2.109524
1     2014           Airton     61985       Botafogo     mei  2.291667
2     2014       Alan Costa     82613  Internacional     zag  1.577778
3     2014     Alan Ruschel     63110  Internacional     lat  4.480000
4     2014      Alan Santos     70132         Santos     mei  0.928571
...    ...              ...       ...            ...     ...       ...
1357  2017     Éder Militão     99424      São Paulo     mei  2.861905
1358  2017          Éderson     73446    Atlético-PR     ata  2.222222
1359  2017            Élber     74140       Cruzeiro     mei  2.476471
1360  2017  Éverton Ribeiro     51772       Flamengo     mei  3.392593
1361  2017            Índio     95180          Sport     ata  1.133333

[1362 rows x 6 columns]